### ISSUE TITLE
Support for Jetpack6.0 Ubuntu22.04

### ISSUE THREAD

**Issue by limshoonkit** [NVIDIA-ISAAC-ROS/isaac_ros_common#110]
Hi, 
https://developer.nvidia.com/embedded/develop/roadmap
Since the Jetpack6.0 developer preview is out, was wondering what are the plans for isaac_ros on jetpack6.0 that is using ubuntu22.04?

is the container image nvcr.io/nvidia/l4t-base:36.2 available?

**Comment by swapnesh-wani-nvidia** [comment]
Support for Ubuntu 22.04 and JetPack 6.0 will be coming in a future release soon. Stay tuned!

**Comment by 00Doc-T** [comment]
What timeframe should we expect? Not having support for Jetpack 6 means it's reasonable to wait to upgrade.

**Comment by rob-pointcloud** [comment]
Hello, can you let us know when Jetpack 6.0 is supported?
