### ISSUE TITLE
error running ./scripts/run_dev.sh

### ISSUE THREAD

**Issue by altineller** [NVIDIA-ISAAC-ROS/isaac_ros_common#12]
Hello,

I am getting this error:

Step 4/39 : RUN apt-get update && apt-get install -y     build-essential     cmake     curl     git     lsb-release     sudo     tar     unzip     vim     wget     software-properties-common && rm -rf /var/lib/apt/lists/*
 ---> Running in 740d45da911d
failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: error adding seccomp filter rule for syscall clone3: permission denied: unknown
Running isaac_ros_dev-aarch64-container
Unable to find image 'isaac_ros_dev-aarch64:latest' locally
docker: Error response from daemon: pull access denied for isaac_ros_dev-aarch64, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
~/isaac_ros_common

I am not sure if there is one error or two errors. Do we need some sort of login procedure?

Best Regards,
C.A.

**Comment by hemalshahNV** [comment]
The "...error adding seccomp filter rule..." part is the real error. This looks like an instance of #5 and the resolution options include upgrading the NVIDIA Container Runtime to 1.7.0 (see https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/issues/5#issuecomment-987554412)
