### ISSUE TITLE
Support JetPack 6.1

### ISSUE THREAD

**Issue by clydemcqueen** [NVIDIA-ISAAC-ROS/isaac_ros_common#154]
I don't see a tracking issue for JetPack 6.1 support, so I thought I'd add one.

Refer to https://forums.developer.nvidia.com/t/getting-error-in-running-the-docker/312503/5

Thanks.

**Comment by mickey13** [comment]
Is there a timeline for supporting JetPack 6.1? I couldn't find one. Thanks.

**Comment by gordongrigor** [comment]
Support for Jetpack 6.1 was released with Isaac ROS 3.2 last week on Dec 10th.  Review the [release notes](https://nvidia-isaac-ros.github.io/releases/index.html) for more details.
