### ISSUE TITLE
does it works with VPI 1.2 and Cuda 11.6 (AMD64)?

### ISSUE THREAD

**Issue by FPSychotic** [NVIDIA-ISAAC-ROS/isaac_ros_common#16]
thanks

**Comment by hemalshahNV** [comment]
CUDA 11.6.1 support on x86_64 with VPI 2.0.14 is planned for the next release of Isaac ROS in June 2022.

**Comment by FPSychotic** [comment]
hi thanks, as there is a big update planned in a short time, I think the best is close all my issues and try the new version when available. 
Feel free to ask if you need a hand in test native installation of the new version.

Cheers and thanks by share

>
