### ISSUE TITLE
Missing keys to docker file x86_64

### ISSUE THREAD

**Issue by hexarotor6** [NVIDIA-ISAAC-ROS/isaac_ros_common#21]
Found out that dockerfile x86_64 is missing the apt keys for script/run_dev.sh to properly work.

added this run line, makes it to work fine it seems
```
 # Fundamentals
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
```

**Comment by hemalshahNV** [comment]
This should be fixed with https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/pull/22
