### ISSUE TITLE
Question: How do I build isaac_ros_* packages inside docker images?

### ISSUE THREAD

**Issue by maxpolzin** [NVIDIA-ISAAC-ROS/isaac_ros_common#27]
Hi,
Thank you for your great work on ROS2 nodes (with CUDA capabilities) for the Jetson boards.
Reading the aarch64 and amd64 docker image files in the repository, they do not seem to compile either of the isaac_ros_* packages. When I understood correctly, those docker images provide a ROS2 installation with CUDA libraries installed. Both architectures, amd64 and aarch64 are possible. 

Should I use them as a base image and build isaac_ros_* packages on top of those images? If yes, they seems to have a lot of ROS2 packages/dependencies in them. Are they all needed?

**Comment by maxpolzin** [comment]
I just noticed the larg update on the repository with commit https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/commit/9da5dc1bef4543d36e8c84aeeb0e60f4baf9329f.

Do you plan to release Docker image with the Isaac ROS packages already built?

**Comment by hemalshahNV** [comment]
Yes, we are preparing to release prebuilt containers shortly. We are reviewing the images to make sure all of the open source licensing are being properly respected.

**Comment by maxpolzin** [comment]
Are the prebuild containers already released? Where will the release be announced?

**Comment by hemalshahNV** [comment]
I'll reply to this thread when ready and there will be a note on the `isaac_ros_common` README.md as well.

**Comment by hemalshahNV** [comment]
The prebuilt images have been released and will get automatically used if you update to the latest `isaac_ros_common` release. `run_dev.sh` will pull them down and use them transparently for you. Here's the [link](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/isaac/containers/ros/tags) to the Docker images on NGC directly for reference.

**Comment by maxpolzin** [comment]
Great. Thx for letting me know. :) 
I will check them out as soon as we need to do apriltag detection again.
