### ISSUE TITLE
torchvision compatibility issue...

### ISSUE THREAD

**Issue by bblumberg** [NVIDIA-ISAAC-ROS/isaac_ros_common#30]
To get torch and torchvision to work (This probably should be documented some place):
1. Binaries from the pytorch website don't use cuda on the agx orin.
2. Follow the instructions to download pytorch wheel from nvidia: https://docs.nvidia.com/deeplearning/frameworks/install-pytorch-jetson-platform/index.html). For what it is worth, I used torch-1.12.0a0+84d1cb9.nv22.4-cp38-cp38-linux_aarch64.whl and not the absolute latest because there was a compatibility issue with yolov5.
3. You must download torchvision and build from source. 
4. For what it is worth, if you use the realsense container, and want to use the python interface, it is pyrealsense2.pyrealsense2, as in: import pyrealsense2.pyrealsense2 as rs

**Comment by hemalshahNV** [comment]
Thanks for working this out! We'll explore updating our Isaac ROS Common images to build torchvision from source directly.

**Comment by jaiveersinghNV** [comment]
The CUDA-enabled version of torch is available in the Isaac ROS Dev base images released in `v0.11.0`, but torchvision was not rebuilt from source.
