### ISSUE TITLE
Example of `.isaac_ros_dev-dockerargs` file

### ISSUE THREAD

**Issue by jainRAV** [NVIDIA-ISAAC-ROS/isaac_ros_common#32]
Hi,

Is there any example of how to set multiple docker args using `.isaac_ros_dev-dockerargs` file?

Thanks

**Comment by hemalshahNV** [comment]
You can just put them on separate lines. For reference, here is our internal version we use that happens to work with the way we setup our environments:
```
-v `realpath ~/.ssh`:/home/admin/.ssh
-v `realpath ~/.cache`:/home/admin/.cache
-v `realpath ~/.config`:/home/admin/.config
--mount type=bind,source="$(realpath ~/.gitconfig)",target=/home/admin/.gitconfig
```
