### ISSUE TITLE
Question: Run on Jetson Nano/Xavier NX

### ISSUE THREAD

**Issue by maxpolzin** [NVIDIA-ISAAC-ROS/isaac_ros_common#33]
Why are the Jetson Xavier NX or Nano not supported? 
Simply because you haven't tried or do they have different architectures?

**Comment by hemalshahNV** [comment]
We haven't qualified our packages on these platforms but there is nothing preventing you from running on them. They have the same architecture and OS but with different compute capabilities (memory, CPU/GPU clock speeds). DNN models that you could load on an AGX Xavier, for example, may not load successfully on a Nano.

**Comment by maxpolzin** [comment]
Great thx for your fast response. If I have time, I try to run some nodes on a Nano and let you know how it goes.

**Comment by jiefengsun** [comment]
@maxpolzin Have you tried? Does it work on Jetson Nano?

**Comment by maxpolzin** [comment]
Hi @jiefengsun, nope, I haven't had time to try it out. Please let me know how it goes if you do.
