### ISSUE TITLE
Tensorflow 1.x in dockerfile x86_64 

### ISSUE THREAD

**Issue by arainbilal** [NVIDIA-ISAAC-ROS/isaac_ros_common#48]
@hemalshahNV  need help in having tensorflow 1.x in x86_64 container, if it is possible. For aarch_64, I can use the guide (https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform/index.html) to have tensoflow 1.x but not found an easy way to have it in the x86_64. 

Thanks in advance for your help.

**Comment by hemalshahNV** [comment]
The following may be helpful for you to setup an installation of Tensorflow 1 for x86_64: https://github.com/NVIDIA/tensorflow. It shows how to use install using Python wheels hosted by NVIDIA or how to build from source on x86_64.

If you haven't already, you can use a custom config file for `run_dev.sh` to add a new item to the image key for a new `Dockerfile.tf1`, something like `humble.nav2.tf1` perhaps (see [here](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common#configuring-run_devsh)).
