### ISSUE TITLE
Support for Humble on Ubuntu 22.04

### ISSUE THREAD

**Issue by rgibbs4545** [NVIDIA-ISAAC-ROS/isaac_ros_common#56]
It seems this is only supported on Ubuntu 20.04 by building Humble from source? Or through the Docker containers which are 20.04?

 Any timeline on issac ros packages and their dependencies being available on 22.04?

**Comment by gordongrigor** [comment]
Correct.

Isaac ROS uses Jetpack 5, which is Ubuntu 20.04.  Jetpack will be updated to Ubuntu 22.04 in Q3-2023.  For more details see the [Jetpack roadmap](https://developer.nvidia.com/embedded/develop/roadmap).

**Comment by rgibbs4545** [comment]
Gotcha. Thanks for the clarification and looking forward to Q3
