### ISSUE TITLE
run_dev.sh always show `Error: Failed to call git rev-parse --git-dir: exit status 128`

### ISSUE THREAD

**Issue by chitoku** [NVIDIA-ISAAC-ROS/isaac_ros_common#58]
Hi,

I noticed that everytime we run `run_dev.sh` it shows this error message at he beginning: 
```
Error: Failed to call git rev-parse --git-dir: exit status 128` at the very beginning
```

It turns out it is coming from [this line](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/main/scripts/run_dev.sh#L81), intended to "Check if all LFS files are in place"
```
# Check if all LFS files are in place
LFS_FILES_STATUS=$(cd $ISAAC_ROS_DEV_DIR && git lfs ls-files | cut -d ' ' -f2)
```
However the `$ISAAC_ROS_DEV_DIR` is `$HOME/workspaces/isaac_ros-dev`, and you can only find git directories under (`$HOME/workspaces/isaac_ros-dev/src/`), so `git lfs ls-files` always fails.

Is this supposed to be checking the `isaac_ros_common` directory, like `LFS_FILES_STATUS=$(cd $ISAAC_ROS_DEV_DIR/src/isaac_ros_common && git lfs ls-files | cut -d ' ' -f2)`?

But I guess that's not enough to check other git directories under the `src` directory.
Perhaps this whole block to check GIT lfs files is not neccesorry?

**Comment by hemalshahNV** [comment]
Thanks, @chitoku ! We have exactly this fix in an upcoming release.
