### ISSUE TITLE
Why is NVIDIA using a proprietary license?

### ISSUE THREAD

**Issue by TakanoTaiga** [NVIDIA-ISAAC-ROS/isaac_ros_common#66]
Are Isaac ROS common and Isaac ROS visual SLAM under NVIDIA's proprietary license instead of the Apache License 2.0? It seems that only these two are under a proprietary license within the Isaac ROS platform. Looking at the commit logs, it appears that other projects are updating when releasing DP2.

**Comment by gordongrigor** [comment]
Great question.  Isaac ROS was initially released under a NV commercial license in 2021. We have been moving code to open source Apache V2.  You have observed that most of Isaac ROS is provided under Apache v2, in DP3 with a few exceptions.
