### ISSUE TITLE
./scripts/run_dev.sh  error

### ISSUE THREAD

**Issue by kong9999** [NVIDIA-ISAAC-ROS/isaac_ros_common#69]
=> ERROR [ 2/10] RUN apt-get update && apt-get install -y         sudo && rm -rf /var/lib/apt/lists/* && apt-get clean               56.5s
------
 > [ 2/10] RUN apt-get update && apt-get install -y         sudo && rm -rf /var/lib/apt/lists/* && apt-get clean:
#0 5.635 Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
#0 5.635 Get:3 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
#0 5.666 Get:4 http://packages.ros.org/ros2-testing/ubuntu focal InRelease [4,685 B]
#0 5.851 Get:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
#0 6.006 Get:7 http://packages.ros.org/ros2-testing/ubuntu focal/main amd64 Packages [1,189 kB]
#0 6.647 Hit:9 http://ppa.launchpad.net/mosquitto-dev/mosquitto-ppa/ubuntu focal InRelease
#0 7.367 Get:10 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
#0 7.420 Get:11 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [1,039 kB]
#0 7.668 Ign:12 https://apt.kitware.com/ubuntu focal InRelease
#0 7.968 Get:13 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1,334 kB]
#0 9.522 Get:14 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [2,203 kB]
#0 9.759 Get:15 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [3,150 kB]
#0 10.32 Err:16 https://apt.kitware.com/ubuntu focal Release
#0 10.32   Certificate verification failed: The certificate is NOT trusted. The received OCSP status response is invalid.  Could not handshake: Error in the certificate verification. [IP: 66.194.253.25 443]
#0 10.39 Get:17 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [28.5 kB]
#0 10.39 Get:18 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2,668 kB]
#0 10.62 Get:1 http://repo.download.nvidia.cn/jetson/x86_64/focal r35.1 InRelease [3,302 B]
#0 10.79 Get:19 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [31.2 kB]
#0 10.79 Get:20 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [2,341 kB]
#0 10.89 Get:21 http://repo.download.nvidia.cn/jetson/x86_64/focal r35.1/main amd64 Packages [26.7 kB]
#0 11.44 Get:22 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [28.6 kB]
#0 11.77 Get:8 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2004/x86_64  InRelease [1,581 B]
#0 11.87 Hit:6 https://packagecloud.io/github/git-lfs/ubuntu focal InRelease
#0 11.88 Get:23 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [55.2 kB]
#0 11.95 Get:24 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2004/x86_64  Packages [1,008 kB]
#0 55.92 Reading package lists...
#0 56.45 E: The repository 'https://apt.kitware.com/ubuntu focal Release' does not have a Release file.
------
Dockerfile.user:18
--------------------
  17 |     # Install prerequisites
  18 | >>> RUN apt-get update && apt-get install -y \
  19 | >>>         sudo \
  20 | >>> && rm -rf /var/lib/apt/lists/* \
  21 | >>> && apt-get clean
  22 |
--------------------
ERROR: failed to solve: process "/bin/bash -c apt-get update && apt-get install -y         sudo && rm -rf /var/lib/apt/lists/* && apt-get clean" did not complete successfully: exit code: 100
Failed to build base image: isaac_ros_dev-x86_64, aborting.
~/workspaces/isaac_ros-dev/src/isaac_ros_common
![image](https://user-images.githubusercontent.com/51771035/236398240-1d3fc68c-2c99-4bc2-8b65-7dd1642a88fb.png)

**Comment by hemalshahNV** [comment]
This seems to be a transient error for the aptitude repository Kitware.com (for cmake).
