### ISSUE TITLE
Build errors with galactic

### ISSUE THREAD

**Issue by benbarron** [NVIDIA-ISAAC-ROS/isaac_ros_common#7]
Hi, I am trying to use this repo and https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline to do hardware acceleration on a Ros2 (galactic) based system that uses realsense cameras. I am using an AGX with ubuntu 18.04 and jetpack 4.6.1. I am running into install errors when building isaac_ros_common inside my base docker image. I noticed the readme says it is designed to be compatible with ros2 foxy. are there any plans to support ros2 galactic? thanks.

**Comment by paulhendricks** [comment]
@hemalshahNV any thoughts on this?

**Comment by hemalshahNV** [comment]
We have not tried to build any of the Isaac ROS packages with Galactic, but I would think the changes required are not too bad if you wanted to try. We support LTS Foxy and we're working with OSRF on improvements for Humble. We do not plan on supporting Galactic in the interim unfortunately.

**Comment by hemalshahNV** [comment]
We will be supporting ROS2 Humble in our upcoming Isaac ROS release.
