### ISSUE TITLE
What is the correct version to install torchvision within ./scripts/run_dev.sh container?

### ISSUE THREAD

**Issue by luvwinnie** [NVIDIA-ISAAC-ROS/isaac_ros_common#70]
I ran the ./scripts/run_dev.sh into a docker container. It seems like pre-installed pytorch v1.13. Can anyone provide a guide to install torchvision within this container ?

**Comment by jaiveersinghNV** [comment]
You will need to download and build `torchvision` from source, as described by another usere [here](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/issues/30#issue-1299424123).
