### ISSUE TITLE
Cannot run container

### ISSUE THREAD

**Issue by reinzler** [NVIDIA-ISAAC-ROS/isaac_ros_common#75]
Hi, I cannot run a container on my Jetson Orin Nano (8gb, Ubuntu 20.04), errors:
admin@tegra-ubuntu:/workspaces/isaac_ros-dev$ colcon test --executor sequential
Starting >>> isaac_ros_common
--- stderr: isaac_ros_common                    
Errors while running CTest
Output from these tests are in: /workspaces/isaac_ros-dev/build/isaac_ros_common/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
---
Finished <<< isaac_ros_common [4.45s]	[ with test failures ]
Starting >>> isaac_ros_test
Finished <<< isaac_ros_test [19.0s]             
Starting >>> isaac_ros_apriltag_interfaces
Finished <<< isaac_ros_apriltag_interfaces [1.72s]            
Starting >>> isaac_ros_bi3d_interfaces
Finished <<< isaac_ros_bi3d_interfaces [1.65s]            
Starting >>> isaac_ros_gxf
Finished <<< isaac_ros_gxf [2.20s]            
Starting >>> isaac_ros_nitros_interfaces
Finished <<< isaac_ros_nitros_interfaces [1.14s]            
Starting >>> isaac_ros_pointcloud_interfaces
Finished <<< isaac_ros_pointcloud_interfaces [1.16s]            
Starting >>> isaac_ros_tensor_list_interfaces
Finished <<< isaac_ros_tensor_list_interfaces [1.56s]            
Starting >>> isaac_ros_visual_slam_interfaces
Finished <<< isaac_ros_visual_slam_interfaces [1.58s]            
Starting >>> isaac_ros_nitros
--- stderr: isaac_ros_nitros                      
Errors while running CTest
Output from these tests are in: /workspaces/isaac_ros-dev/build/isaac_ros_nitros/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
---
Finished <<< isaac_ros_nitros [15.7s]	[ with test failures ]
Starting >>> isaac_ros_nitros_april_tag_detection_array_type
[51.816s] ERROR:colcon.colcon_cmake.task.cmake.test:Failed to find the following files:
- /workspaces/isaac_ros-dev/install/isaac_ros_nitros_april_tag_detection_array_type/share/isaac_ros_nitros_april_tag_detection_array_type/package.sh
Check that the following packages have been built:
- isaac_ros_nitros_april_tag_detection_array_type
Failed   <<< isaac_ros_nitros_april_tag_detection_array_type [0.03s, exited with code 1]
Starting >>> isaac_ros_nitros_camera_info_type
[51.846s] ERROR:colcon.colcon_cmake.task.cmake.test:Failed to find the following files:
- /workspaces/isaac_ros-dev/install/isaac_ros_nitros_camera_info_type/share/isaac_ros_nitros_camera_info_type/package.sh
Check that the following packages have been built:
- isaac_ros_nitros_camera_info_type
Failed   <<< isaac_ros_nitros_camera_info_type [0.02s, exited with code 1]
Starting >>> isaac_ros_nitros_compressed_image_type
--- stderr: isaac_ros_nitros_compressed_image_type
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_cmake/test.py", line 29, in test
    return await extension.test()
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/test.py", line 45, in test
    assert os.path.exists(args.build_base), \
AssertionError: Has this package been built before?
---
Failed   <<< isaac_ros_nitros_compressed_image_type [0.00s, exited with code 1]
[51.853s] ERROR:colcon.colcon_core.executor.sequential:Exception in job execution 'isaac_ros_nitros_compressed_image_type': Has this package been built before?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/sequential.py", line 48, in execute
    loop.run_until_complete(future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_cmake/test.py", line 29, in test
    return await extension.test()
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/test.py", line 45, in test
    assert os.path.exists(args.build_base), \
AssertionError: Has this package been built before?

Summary: 10 packages finished [51.0s]
  3 packages failed: isaac_ros_nitros_april_tag_detection_array_type isaac_ros_nitros_camera_info_type isaac_ros_nitros_compressed_image_type
  3 packages had stderr output: isaac_ros_common isaac_ros_nitros isaac_ros_nitros_compressed_image_type
  2 packages had test failures: isaac_ros_common isaac_ros_nitros
  12 packages not processed

**Comment by jaiveersinghNV** [comment]
Could you please provide the full logs that accompany the test failure? You can either run with the verbose flag `--output-on-failure` or provide the full file from `/workspaces/isaac_ros-dev/build/[PACKAGE]/Testing/Temporary/LastTest.log`.

Some things to check:
- Did you build the workspace prior to running the test? `colcon build`
- Did you source the workspace? `source install/setup.bash`
- Have you tried cleaning the workspace and rebuilding/retesting? `rm -rf build/ install/ log/` and repeat
