### ISSUE TITLE
Install additional ROS packages

### ISSUE THREAD

**Issue by Fibo27** [NVIDIA-ISAAC-ROS/isaac_ros_common#77]
Hi

I would like to customize the docker by adding additional ROS packages which are not installed in the library. Usually I use the following syntax 
sudo apt-get install ros-humblevision-msgs \
                               apt-install-ros-humble-joint-state-publisher-gui
                               python3-colcon-common-extensions  
and etc
Can you please suggest how to go about modifying the build script?

**Comment by swapnesh-wani-nvidia** [comment]
Hello, Isaac ROS has ROS2 Humble built from the source. You have to build your desired packages from the source. Have a look at [this docker file](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/main/docker/Dockerfile.ros2_humble) for your reference.
