### ISSUE TITLE
isaac ros with cuda 12.0

### ISSUE THREAD

**Issue by Gongsta** [NVIDIA-ISAAC-ROS/isaac_ros_common#78]
Hi there, I'm looking to integrate https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/tree/master/CUDA-BEVFusion into ROS2 humble. I managed to get it running without ROS using the `nvcr.io/nvidia/tensorrt:23.01-py3` docker image, which runs cuda-12.0. I wasn't able to get it running on cuda-12.1.

I've been trying to use the Isaac ROS docker images, which have both Cuda and ROS humble installed. However, it seems that all of them run on cuda-12.1. I've tried all the containers here: https://catalog.ngc.nvidia.com/orgs/nvidia/teams/isaac/containers/ros/tags, the oldest one also has cuda-12.1 even though it was released last year (I thought cuda-12.1 was only released this year..?)

Is there one for cuda-12.0 + ros humble?

**Comment by swapnesh-wani-nvidia** [comment]
Hello, the latest Isaac ROS docker images have CUDA toolkit version 11.8 on x86 and 11.4 on Jetson platform. You can try to manually upgrade the CUDA toolkit version within the container to the desired version. Do note that upon exiting the container, you may lose all the system changes that you might have done inside the container. You can introduce the CUDA toolkit updation as another docker layer of your own as shown [here](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common#configuring-run_devsh).
