### ISSUE TITLE
Missing of rqt common plugins except ImageView?

### ISSUE THREAD

**Issue by luvwinnie** [NVIDIA-ISAAC-ROS/isaac_ros_common#88]
I'm using isaac_ros_common/scripts/run_dev.sh to build a docker container for development environment, however it seems like it missing the essential tools like rqt_graph and other rqt common plugins. Is there anyway to add those plugin? I can't add those since I'm using Jetson with version ubuntu20.04's JetPack.

**Comment by jaiveersinghNV** [comment]
With our [latest release](https://nvidia-isaac-ros.github.io/releases/index#isaac-ros-2-0-0-october-18-2023), we use the new Isaac ROS Buildfarm to produce precompiled Debian packages for popular ROS packages on JetPack. Could you please try the latest release? You should then be able to install standard plugins like `rqt_graph`:

```
sudo apt-get install ros2-humble-rqt-common-plugins
```
