### ISSUE TITLE
Can't load container

### ISSUE THREAD

**Issue by IAMHAADICOOL** [NVIDIA-ISAAC-ROS/isaac_ros_common#94]
Do I need to build container everytime I wish to run a issac_ros_package?
    isaac_ros_container
The above command is not working

**Comment by swapnesh-wani-nvidia** [comment]
Hi, could you add the command that is not working for you and the logs?
As for the container, you don't need to build it. `scripts/run_dev.sh` pulls (and gets cached by docker) the container for you and provides you with a terminal interface. If you exit the container and execute the script again it will use the cached image to bring up the isaac_ros environment.
